### ISSUE TITLE
Mix Monitor option on Monitor

### ISSUE THREAD

**Issue by fredcwbr** [dmitriyborisenko/Astergazer#3]
Dear Dmtri,

Congratulations for the really great work in AsterGazer,
Started to use it yesterday, and already in a custom IVR without great problems.

One thing that I needed thougth is to use MixMonitor instead of Monitor, and
was wondering where/how to change this in the dialplan blocks.,
Is there some kind of options/config for thtat or should I just go to the code?

Thanks in advance.
Regards from Brazil

Frederico C Wilhelms

**Comment by fredcwbr** [comment]
Please disregard this comment about need to mix monitor.,
Missed the  the MixMonitor button on the panel., 
My bad., 

**
Again,

Congrats for the superb job.,

**Comment by dmitriyborisenko** [comment]
Hi Frederico,

Thanks for your feedback.
Yes, there is a block for the MixMonitor.
But I want to notice that if you need to use some dialplan application which is not implemented with a corresponding block you can simply use the "Custom" block (it has the icon with a gray box in the middle) and write any code inside of the "Custom Command" field. As instance, to use it for MixMonitor you just should write something like `MixMonitor(${MONITOR_FILENAME},b,)` without of "exten = " or "same = " prefixes.

With best regards,
Dmitriy Borisenko
